# Generated by Django 6.0.7 on 2026-07-25 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=20, unique=True, verbose_name='Project/Site Code')),
                ('project_name', models.CharField(max_length=150, verbose_name='Site Name')),
                ('location_city', models.CharField(max_length=50, verbose_name='City/Region')),
                ('is_active', models.BooleanField(default=True, verbose_name='Site Active Status')),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer', verbose_name='Assigned Client')),
            ],
            options={
                'verbose_name': 'Project Site',
                'verbose_name_plural': 'Project Sites',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_site', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('released_date', models.DateField(blank=True, help_text='Leave blank if the employee is currently active at this site.', null=True)),
                ('is_current_assignment', models.BooleanField(default=True, help_text='Uncheck this if the employee has completed their work at this site.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeemaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Work Site Assignment',
                'verbose_name_plural': 'Work Site Assignments',
                'unique_together': {('employee', 'project', 'assigned_date')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='assigned_projects', through='projects.ProjectAssignment', to='employees.employeemaster'),
        ),
    ]
