# Generated by Django 6.0.7 on 2026-07-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='cost_center',
        ),
    ]
