# Generated by Django 6.0.7 on 2026-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='Client Code')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company/Client Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Representative')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='VAT / Tax Number')),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
            },
        ),
    ]
