# Generated by Django 6.0.7 on 2026-08-03 06:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_employeemaster_email_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='e.g., Standard 8-Hour Site Shift')),
                ('standard_start_time', models.TimeField(help_text='Standard daily check-in time')),
                ('standard_end_time', models.TimeField(help_text='Standard daily check-out time')),
                ('expected_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Working Hours Schedule',
                'verbose_name_plural': 'Working Hours Schedules',
            },
        ),
        migrations.CreateModel(
            name='SiteScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='projects.project')),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.workinghours')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('regular_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('overtime_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Dashboard Entry'), ('WHATSAPP', 'Automated WhatsApp API Vector')], default='MANUAL', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employeemaster')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Attendance Entry',
                'verbose_name_plural': 'Attendance Entries',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
