# Generated by Django 6.0.7 on 2026-07-25 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Format must be: '+9665XXXXXXXX'", regex='^\\+9665\\d{8}$')])),
                ('blood_group', models.CharField(blank=True, help_text='e.g., O+, A-', max_length=5, null=True)),
                ('iqama_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Iqama / National ID')),
                ('iqama_expiry_gregorian', models.DateField(blank=True, null=True, verbose_name='Iqama Expiry (Gregorian)')),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('passport_expiry_date', models.DateField(verbose_name='Passport Expiry Date')),
                ('id_expiry_date', models.DateField(verbose_name='Company ID Expiry Date')),
                ('last_transfer_date', models.DateField(blank=True, help_text='Date relocated to current site', null=True)),
                ('transportation_mode', models.CharField(blank=True, help_text='e.g., Company Bus, Flight', max_length=50, null=True)),
                ('last_leave_start_date', models.DateField(blank=True, null=True)),
                ('last_leave_end_date', models.DateField(blank=True, null=True)),
                ('next_planned_leave', models.DateField(blank=True, null=True)),
                ('leaves_allocated', models.PositiveIntegerField(default=30, help_text='Total annual leave quota')),
                ('leaves_used', models.PositiveIntegerField(default=0)),
                ('nearest_airport_ksa', models.CharField(help_text='Nearest airport to work site (e.g., JED, RUH, DMM)', max_length=50)),
                ('home_country_airport', models.CharField(help_text='Destination airport in home country', max_length=100)),
                ('last_air_fare_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in SAR', max_digits=10, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Home Country Contact Name')),
                ('emergency_contact_relationship', models.CharField(max_length=50, verbose_name='Relationship (e.g., Spouse, Parent)')),
                ('emergency_contact_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="International phone must start with '+' followed by 7 to 15 digits.", regex='^\\+\\d{7,15}$')], verbose_name='Home Country Phone')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Master Record',
                'verbose_name_plural': 'Employee Master Records',
            },
        ),
    ]
