# Generated by Django 6.0.7 on 2026-07-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department', verbose_name='Assigned Department'),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Employee ID'),
        ),
    ]
