# Generated by Django 6.0.7 on 2026-07-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeemaster_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='passport_expiry_date',
            field=models.DateField(null=True, verbose_name='Passport Expiry Date'),
        ),
    ]
