# Generated by Django 6.0.7 on 2026-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeemaster_passport_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Company ID Expiry Date'),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
