# Generated by Django 6.0.7 on 2026-07-29 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeemaster_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Format must be: '05XXXXXXXX'", regex='^\\05\\d{8}$')]),
        ),
    ]
