# Generated by Django 6.0.7 on 2026-08-05 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeemaster_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Format must be: '+9665XXXXXXXX'", regex='^\\+9665\\d{8}$')]),
        ),
    ]
